# Generated by Django 4.2.28 on 2026-02-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('badge_en', models.CharField(blank=True, max_length=100)),
                ('price_en', models.CharField(blank=True, max_length=50)),
                ('features_en', models.JSONField(blank=True, default=list)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('short_description_ar', models.TextField(blank=True)),
                ('badge_ar', models.CharField(blank=True, max_length=100)),
                ('price_ar', models.CharField(blank=True, max_length=50)),
                ('features_ar', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
